name: Build
on:
  pull_request:
    branches:
      - main

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Verify README generation
        uses: momentohq/standards-and-practices/github-actions/oss-readme-template@gh-actions-v2
        with:
          project_status: official
          project_stability: alpha
          project_type: other

  test:
    strategy:
      matrix:
        node: [16, 18, 20]
    name: Test on Node ${{ matrix.node }}
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm

      - name: Install dependencies
        run: |
          npm ci
          node -v

      - name: Build
        run: npm run build

      - name: Lint
        run: npm run lint

